trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: sudo apt install nodejs
  displayName: 'Install Node.js'

- script: npm i
  displayName: 'Install dependencies'

- script: |
    sudo echo "registry=https://yoguisan.pkgs.visualstudio.com/_packaging/yoguisan/npm/registry/
    ; begin auth token
    //yoguisan.pkgs.visualstudio.com/_packaging/yoguisan/npm/registry/:username=yoguisan
    //yoguisan.pkgs.visualstudio.com/_packaging/yoguisan/npm/registry/:_password=$AZURE_PAT
    //yoguisan.pkgs.visualstudio.com/_packaging/yoguisan/npm/registry/:email=npm requires email to be set but doesn't use the value
    //yoguisan.pkgs.visualstudio.com/_packaging/yoguisan/npm/:username=yoguisan
    //yoguisan.pkgs.visualstudio.com/_packaging/yoguisan/npm/:_password=$AZURE_PAT
    //yoguisan.pkgs.visualstudio.com/_packaging/yoguisan/npm/:email=npm requires email to be set but doesn't use the value
    ; end auth token
    " > .npmrc
  displayName: 'Setup repository'

- script: npm run build
  displayName: 'Build'