trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: sudo apt install nodejs
  displayName: 'Install Node.js'

- script: npm i
  displayName: 'Install dependencies'

- script: ./scripts/generate-npmrc.sh
  displayName: 'Setup repository'
- script: |
    npm run build
  displayName: 'Build'