/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EuiButton {
        "classes": any;
        "color": any;
        "fontColor": any;
        "fullWidth": boolean;
        "icon": any;
        "onClick": any;
        "padding": any;
        "styles": any;
        "text": any;
        "type": any;
        "variant": any;
    }
    interface EuiGrid {
        "columns"?: number;
        "container"?: boolean;
        "extralarge"?: number;
        "extrasmall"?: number;
        "gap"?: number;
        "large"?: number;
        "medium"?: number;
        "small"?: number;
    }
}
declare global {
    interface HTMLEuiButtonElement extends Components.EuiButton, HTMLStencilElement {
    }
    var HTMLEuiButtonElement: {
        prototype: HTMLEuiButtonElement;
        new (): HTMLEuiButtonElement;
    };
    interface HTMLEuiGridElement extends Components.EuiGrid, HTMLStencilElement {
    }
    var HTMLEuiGridElement: {
        prototype: HTMLEuiGridElement;
        new (): HTMLEuiGridElement;
    };
    interface HTMLElementTagNameMap {
        "eui-button": HTMLEuiButtonElement;
        "eui-grid": HTMLEuiGridElement;
    }
}
declare namespace LocalJSX {
    interface EuiButton {
        "classes"?: any;
        "color"?: any;
        "fontColor"?: any;
        "fullWidth"?: boolean;
        "icon"?: any;
        "onClick"?: any;
        "padding"?: any;
        "styles"?: any;
        "text"?: any;
        "type"?: any;
        "variant"?: any;
    }
    interface EuiGrid {
        "columns"?: number;
        "container"?: boolean;
        "extralarge"?: number;
        "extrasmall"?: number;
        "gap"?: number;
        "large"?: number;
        "medium"?: number;
        "small"?: number;
    }
    interface IntrinsicElements {
        "eui-button": EuiButton;
        "eui-grid": EuiGrid;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "eui-button": LocalJSX.EuiButton & JSXBase.HTMLAttributes<HTMLEuiButtonElement>;
            "eui-grid": LocalJSX.EuiGrid & JSXBase.HTMLAttributes<HTMLEuiGridElement>;
        }
    }
}
