/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EuiButton {
        "classes": any;
        /**
          * @default 'lightgray'
         */
        "color": string;
        "fontColor": any;
        "fullwidth": any;
        "icon": any;
        "onClick": any;
        "padding": any;
        "styles": any;
        "text": any;
        "type": any;
        "variant": any;
    }
    interface EuiCard {
        "iconBgColor": any;
        "title": any;
    }
    interface EuiFigure {
        "alt": any;
        "backgroundImage": any;
        "caption": any;
        /**
          * @default ''
         */
        "classes": string;
        "src": any;
        "url": any;
    }
    interface EuiGrid {
        "classes": any;
        "columns": any;
        "condensed": any;
        "container": any;
        "extralarge": any;
        "extrasmall": any;
        "flexDirection": any;
        "gap": any;
        "justifyContent": any;
        "large": any;
        "medium": any;
        "narrow": any;
        "rendered": boolean;
        "resizeHandler"?: void;
        "small": any;
    }
}
declare global {
    interface HTMLEuiButtonElement extends Components.EuiButton, HTMLStencilElement {
    }
    var HTMLEuiButtonElement: {
        prototype: HTMLEuiButtonElement;
        new (): HTMLEuiButtonElement;
    };
    interface HTMLEuiCardElement extends Components.EuiCard, HTMLStencilElement {
    }
    var HTMLEuiCardElement: {
        prototype: HTMLEuiCardElement;
        new (): HTMLEuiCardElement;
    };
    interface HTMLEuiFigureElement extends Components.EuiFigure, HTMLStencilElement {
    }
    var HTMLEuiFigureElement: {
        prototype: HTMLEuiFigureElement;
        new (): HTMLEuiFigureElement;
    };
    interface HTMLEuiGridElement extends Components.EuiGrid, HTMLStencilElement {
    }
    var HTMLEuiGridElement: {
        prototype: HTMLEuiGridElement;
        new (): HTMLEuiGridElement;
    };
    interface HTMLElementTagNameMap {
        "eui-button": HTMLEuiButtonElement;
        "eui-card": HTMLEuiCardElement;
        "eui-figure": HTMLEuiFigureElement;
        "eui-grid": HTMLEuiGridElement;
    }
}
declare namespace LocalJSX {
    interface EuiButton {
        "classes"?: any;
        /**
          * @default 'lightgray'
         */
        "color"?: string;
        "fontColor"?: any;
        "fullwidth"?: any;
        "icon"?: any;
        "onClick"?: any;
        "padding"?: any;
        "styles"?: any;
        "text"?: any;
        "type"?: any;
        "variant"?: any;
    }
    interface EuiCard {
        "iconBgColor"?: any;
        "title"?: any;
    }
    interface EuiFigure {
        "alt"?: any;
        "backgroundImage"?: any;
        "caption"?: any;
        /**
          * @default ''
         */
        "classes"?: string;
        "src"?: any;
        "url"?: any;
    }
    interface EuiGrid {
        "classes"?: any;
        "columns"?: any;
        "condensed"?: any;
        "container"?: any;
        "extralarge"?: any;
        "extrasmall"?: any;
        "flexDirection"?: any;
        "gap"?: any;
        "justifyContent"?: any;
        "large"?: any;
        "medium"?: any;
        "narrow"?: any;
        "rendered"?: boolean;
        "resizeHandler"?: void;
        "small"?: any;
    }
    interface IntrinsicElements {
        "eui-button": EuiButton;
        "eui-card": EuiCard;
        "eui-figure": EuiFigure;
        "eui-grid": EuiGrid;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "eui-button": LocalJSX.EuiButton & JSXBase.HTMLAttributes<HTMLEuiButtonElement>;
            "eui-card": LocalJSX.EuiCard & JSXBase.HTMLAttributes<HTMLEuiCardElement>;
            "eui-figure": LocalJSX.EuiFigure & JSXBase.HTMLAttributes<HTMLEuiFigureElement>;
            "eui-grid": LocalJSX.EuiGrid & JSXBase.HTMLAttributes<HTMLEuiGridElement>;
        }
    }
}
